spring:
  application:
    name: QuoraApp
  data:
    mongodb:
      host: localhost
      port: 27017
      database: quora_db
      #   I've no username/password currently
      #    username: root
      #    password: root
    auto-index-creation: true



  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: view-count-consumer
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.example.quora.events.ViewCountEvent

  elasticsearch:
    uris: http://localhost:9200